### ISSUE TITLE
Website no responsive

### ISSUE THREAD

**Issue by EzequielPriotto** [ElCaptus/May_App#6]
Al querer acceder desde mi dispositivo movil note que la pagina no esta diseñada para mi dispositivo

![image](https://user-images.githubusercontent.com/94701486/173854210-840a8af5-df4c-48a2-8f9f-965e9c71ee6a.png)

Ademas la vista mobile no tiene barra de navegacion, limitando asi la posibilidad de recorrer el sitio de forma comoda.

![image](https://user-images.githubusercontent.com/94701486/173854720-3bf6c014-b113-4340-9a84-1ab277c85559.png)

Te recomiendo realizar los proyectos siempre mobile first, haciendo asi mas sencilla la produccion para cualquier dispositivoツ

Saludos mi buen amigo!
Atte:  Seven.

**Comment by ElCaptus** [comment]
Gracias por las recomendaciones. 
- La side bar para navegación Mobile no esta dentro de mis planes. La navegación al repositorio de GitHub no es uno de mis objetivos en Mobile.

- El responsive design, como ya lo discutimos, fue un error en tu teléfono en el momento y luego se arreglo.

Gracias por tu contribución <3
Your friendly neighborhood, **Captus!**
